name: msml-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas
  - numpy
  - scikit-learn
  - imbalanced-learn
  - matplotlib
  - seaborn
  - joblib
  - pip:
    - mlflow
    - dagshub
    - cloudpickle
    - scikit-optimize
