name: Model Training and Logging

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MLProject/requirements.txt

    - name: Run the model training
      run: |
        python MLProject/modelling.py

    - name: Log to MLflow
      run: |
        mlflow ui  # Ini untuk menjalankan UI MLflow
