name: mlflow-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - scikit-learn
  - mlflow
  - matplotlib
  - seaborn
  - pip
  - pip:
      - imbalanced-learn
      - dagshub
